[package]
name = "af"
version = "0.0.3"
authors = ["Ridwan Hoq <ridhoq@users.noreply.github.com>"]
edition = "2018"
description = "A (http) fetch CLI ğŸ˜€ğŸ‘ğŸ½"
license = "MIT"
repository = "https://github.com/ridhoq/af"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
http = "0.2.2"
hyper = { version = "0.14", features = ["full"] }
hyper-tls = "0.5.0"
tokio = { version = "1", features = ["full"] }
